### ISSUE TITLE
Why compile error?

### ISSUE THREAD

**Issue by xzajyjs** [JohnLulzh2002/BoringHomeworks#1]

**Comment by xzajyjs** [comment]
compile error

**Comment by xzajyjs** [comment]
**P1128 and P1242**

**Comment by JohnLulzh2002** [comment]
I've tested on my computer and on Luogu IDE, and it seemed OK.

Please provide me the warning or error message that the compiler shows.

---

If you use VisualStudio, make sure the code below is added at the beginning.
```c
#define _CRT_SECURE_NO_WARNINGS
```

**Comment by xzajyjs** [comment]
OJ says it's complied error.I copy it on the hand-in-sub directly.

**Comment by xzajyjs** [comment]
<img width="512" alt="截屏2021-06-06 17 30 05" src="https://user-images.githubusercontent.com/25580455/120919559-d6027980-c6ec-11eb-9313-5a1e21b70e7a.png">

**Comment by xzajyjs** [comment]
<img width="388" alt="截屏2021-06-06 17 30 27" src="https://user-images.githubusercontent.com/25580455/120919568-e3b7ff00-c6ec-11eb-9aa8-6be03473f6a4.png">
There are two errors in viscose

**Comment by xzajyjs** [comment]
> <img alt="截屏2021-06-06 17 30 27" width="388" src="https://user-images.githubusercontent.com/25580455/120919568-e3b7ff00-c6ec-11eb-9aa8-6be03473f6a4.png">
> 
> There are two errors in viscose

this is P1128
